/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTeacherRouteImport } from './routes/auth.teacher'
import { Route as AuthStudentRouteImport } from './routes/auth.student'
import { Route as AuthParentRouteImport } from './routes/auth.parent'
import { Route as AuthAdminRouteImport } from './routes/auth.admin'
import { Route as ApiAiTutorStreamRouteImport } from './routes/api/ai-tutor-stream'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated.teacher'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as StudentExamAttemptIdRouteImport } from './routes/student.exam.$attemptId'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as VerifySerialRouteImport } from './routes/verify.$serial'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTeacherRoute = AuthTeacherRouteImport.update({
  id: '/auth/teacher',
  path: '/auth/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStudentRoute = AuthStudentRouteImport.update({
  id: '/auth/student',
  path: '/auth/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthParentRoute = AuthParentRouteImport.update({
  id: '/auth/parent',
  path: '/auth/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTutorStreamRoute = ApiAiTutorStreamRouteImport.update({
  id: '/api/ai-tutor-stream',
  path: '/api/ai-tutor-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const StudentExamAttemptIdRoute = StudentExamAttemptIdRouteImport.update({
  id: '/student/exam/$attemptId',
  path: '/student/exam/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifySerialRoute = VerifySerialRouteImport.update({
  id: '/verify/$serial',
  path: '/verify/$serial',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/api/ai-tutor-stream': typeof ApiAiTutorStreamRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/parent': typeof AuthParentRoute
  '/auth/student': typeof AuthStudentRoute
  '/auth/teacher': typeof AuthTeacherRoute
  '/student/exam/$attemptId': typeof StudentExamAttemptIdRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/verify/$serial': typeof VerifySerialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/api/ai-tutor-stream': typeof ApiAiTutorStreamRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/parent': typeof AuthParentRoute
  '/auth/student': typeof AuthStudentRoute
  '/auth/teacher': typeof AuthTeacherRoute
  '/student/exam/$attemptId': typeof StudentExamAttemptIdRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/verify/$serial': typeof VerifySerialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/api/ai-tutor-stream': typeof ApiAiTutorStreamRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/parent': typeof AuthParentRoute
  '/auth/student': typeof AuthStudentRoute
  '/auth/teacher': typeof AuthTeacherRoute
  '/student/exam/$attemptId': typeof StudentExamAttemptIdRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/verify/$serial': typeof VerifySerialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/teacher'
    | '/api/ai-tutor-stream'
    | '/auth/admin'
    | '/auth/parent'
    | '/auth/student'
    | '/auth/teacher'
    | '/student/exam/$attemptId'
    | '/student/dashboard'
    | '/verify/$serial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/teacher'
    | '/api/ai-tutor-stream'
    | '/auth/admin'
    | '/auth/parent'
    | '/auth/student'
    | '/auth/teacher'
    | '/student/exam/$attemptId'
    | '/student/dashboard'
    | '/verify/$serial'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/teacher'
    | '/api/ai-tutor-stream'
    | '/auth/admin'
    | '/auth/parent'
    | '/auth/student'
    | '/auth/teacher'
    | '/student/exam/$attemptId'
    | '/student/dashboard'
    | '/verify/$serial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiAiTutorStreamRoute: typeof ApiAiTutorStreamRoute
  AuthAdminRoute: typeof AuthAdminRoute
  AuthParentRoute: typeof AuthParentRoute
  AuthStudentRoute: typeof AuthStudentRoute
  AuthTeacherRoute: typeof AuthTeacherRoute
  StudentExamAttemptIdRoute: typeof StudentExamAttemptIdRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  VerifySerialRoute: typeof VerifySerialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/teacher': {
      id: '/auth/teacher'
      path: '/auth/teacher'
      fullPath: '/auth/teacher'
      preLoaderRoute: typeof AuthTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/student': {
      id: '/auth/student'
      path: '/auth/student'
      fullPath: '/auth/student'
      preLoaderRoute: typeof AuthStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/parent': {
      id: '/auth/parent'
      path: '/auth/parent'
      fullPath: '/auth/parent'
      preLoaderRoute: typeof AuthParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-tutor-stream': {
      id: '/api/ai-tutor-stream'
      path: '/api/ai-tutor-stream'
      fullPath: '/api/ai-tutor-stream'
      preLoaderRoute: typeof ApiAiTutorStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/student/exam/$attemptId': {
      id: '/student/exam/$attemptId'
      path: '/student/exam/$attemptId'
      fullPath: '/student/exam/$attemptId'
      preLoaderRoute: typeof StudentExamAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$serial': {
      id: '/verify/$serial'
      path: '/verify/$serial'
      fullPath: '/verify/$serial'
      preLoaderRoute: typeof VerifySerialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiAiTutorStreamRoute: ApiAiTutorStreamRoute,
  AuthAdminRoute: AuthAdminRoute,
  AuthParentRoute: AuthParentRoute,
  AuthStudentRoute: AuthStudentRoute,
  AuthTeacherRoute: AuthTeacherRoute,
  StudentExamAttemptIdRoute: StudentExamAttemptIdRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  VerifySerialRoute: VerifySerialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
